# Generated by Django 2.1.7 on 2019-04-04 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20190404_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单号')),
                ('order_status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已取消')], default=0, verbose_name='订单状态')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='订单总价')),
                ('order_desc', models.CharField(max_length=120, verbose_name='订单描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='订单支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'ly_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程购买价格')),
                ('effective_time', models.SmallIntegerField(choices=[(0, '永久有效'), (1, '1个月有效'), (2, '2个月有效'), (3, '3个月有效'), (4, '6个月有效'), (5, '12个月有效')], default=2, verbose_name='有效期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_order', to='courses.Course', verbose_name='课程ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_course', to='orders.Order', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'ly_order_detail',
            },
        ),
    ]
