# Generated by Django 2.1.7 on 2019-04-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='effective_time',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='odetail_user', to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_user', to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='lf_order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='lf_order_detail',
        ),
    ]
