# Generated by Django 2.1.7 on 2019-03-31 15:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=128, verbose_name='课程名称')),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='课程封面图')),
                ('course_type', models.SmallIntegerField(choices=[(0, '免费'), (1, '付费'), (2, 'VPI专享'), (3, '学位课程')], verbose_name='付费类型')),
                ('brief', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='课程介绍')),
                ('level', models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=1, verbose_name='课程难度等级')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('preiod', models.IntegerField(default=7, verbose_name='建议学习周期(day)')),
                ('order', models.IntegerField(verbose_name='课程排序')),
                ('attachment_path', models.FileField(blank=True, max_length=128, null=True, upload_to='', verbose_name='课件路径')),
                ('status', models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0, verbose_name='课程状态')),
                ('studys', models.IntegerField(default=0, verbose_name='学习人数')),
                ('lessons', models.IntegerField(default=0, verbose_name='总课程数量')),
                ('pub_lessons', models.IntegerField(default=0, verbose_name='课程更新数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='课程原价')),
            ],
            options={
                'verbose_name': '专题课程',
                'verbose_name_plural': '专题课程',
                'db_table': 'lf_course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='分类名称')),
                ('order', models.IntegerField(null=True, verbose_name='分类排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上线')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'lf_course_category',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('chapter', models.SmallIntegerField(default=0, verbose_name='课程章节')),
                ('name', models.CharField(max_length=128, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='章节介绍')),
                ('pubdate', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursechapters', to='courses.Course', verbose_name='章节标题')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'lf_course_chapter',
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=128, verbose_name='课时标题')),
                ('order', models.PositiveSmallIntegerField(verbose_name='课时排序')),
                ('section_type', models.SmallIntegerField(choices=[(0, '文档'), (1, '练习'), (2, '视频')], default=2, verbose_name='课时种类')),
                ('section_link', models.CharField(blank=True, help_text='若是video，填vid,若是文档，填link', max_length=255, null=True, verbose_name='课时链接')),
                ('duration', models.CharField(blank=True, max_length=32, null=True, verbose_name='视频时长')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('free_trial', models.BooleanField(default=False, verbose_name='是否可以试看')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上线')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesections', to='courses.CourseChapter')),
            ],
            options={
                'verbose_name': '课程课时',
                'verbose_name_plural': '课程课时',
                'db_table': 'lf_course_lesson',
            },
        ),
        migrations.CreateModel(
            name='PricePolicyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('condition', models.IntegerField(verbose_name='满足优惠条件的价格')),
                ('policy_type', models.SmallIntegerField(choices=[(0, '积分兑换'), (1, '折扣优惠'), (2, '限时免费')], verbose_name='优惠类型')),
                ('policy_value', models.IntegerField(help_text='如果是积分兑换优惠，则填写的值为可以兑换的最大积分；<br /> 如果是折扣优惠则填写折扣的百分比值，如8折则填写80; <br /> 如果是限时免费，则可以不填', verbose_name='优惠值（根据优惠类型来填写）')),
                ('start_time', models.DateTimeField(verbose_name='优惠策略的开始时间')),
                ('end_time', models.DateTimeField(verbose_name='优惠策略的结束时间')),
            ],
            options={
                'verbose_name': '价格服务策略',
                'verbose_name_plural': '价格服务策略',
                'db_table': 'lf_price_policy_service',
            },
        ),
        migrations.CreateModel(
            name='PriceServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=32, verbose_name='服务类型名称')),
            ],
            options={
                'verbose_name': '价格服务',
                'verbose_name_plural': '价格服务',
                'db_table': 'lf_price_service_type',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=32, verbose_name='讲师名字')),
                ('role', models.SmallIntegerField(choices=[(0, '讲师'), (1, '导师')], default=0, verbose_name='讲师身份（角色）')),
                ('title', models.CharField(max_length=64, verbose_name='讲师职位，职称')),
                ('signature', models.CharField(blank=True, help_text='讲师签名', max_length=255, null=True, verbose_name='讲师签名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher', verbose_name='讲师封面')),
                ('brief', models.TextField(max_length=1024, verbose_name='讲师描述')),
            ],
            options={
                'verbose_name': '讲师、导师',
                'verbose_name_plural': '讲师、导师',
                'db_table': 'lf_teacher',
            },
        ),
        migrations.AddField(
            model_name='pricepolicyservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricepolicy', to='courses.PriceServiceType', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_service_type',
            field=models.ManyToManyField(to='courses.PriceServiceType', verbose_name='价格服务类型'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Teacher', verbose_name='授课老师'),
        ),
    ]
